# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Goose of the Woods
description: >- # this means to ignore newlines until "baseurl:"
  Our portal to nowhere
baseurl: "" # the subpath of the site
url: "https://gooseofthewoods.earth" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "G-4VTQNMXXJE"
imagesurl: "/assets/img/mooches/"

header:
  pages:
    - name: Home
      slug: /
    - name: Mooches
    - name: Projects
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: geese@gooseofthewoods.earth
  follow:
    - type: github
      name: GitHub
      link: http://github.com/loonglade

# Build settings
markdown: kramdown
sass:
    style: compressed
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
